name: Document Site Publish

on:
  push:
    branches: [ "master" ]

permissions:
  pages: write
  id-token: write

jobs:
  publish-docs:
    uses: JaCraig/Centralized-Workflows/.github/workflows/docsfx.yml@main
